AddEventHandler("Phone:Server:RegisterCallbacks", function()
	plsr.Callbacks:RegisterServerCallback("Phone:Media:GetMedia", function(source, data, cb)
		cb(plsr.Photos:Fetch(source))
	end)
	plsr.Callbacks:RegisterServerCallback("Phone:Media:DeleteMedia", function(source, data, cb)
		cb(plsr.Photos:Delete(source, data.id))
	end)
end)
